require("configs.colorscheme")
require("configs.lualine")
require("configs.treesitter")
require("configs.nvim-tree")
require("configs.undotree")
require("configs.gitsigns")
require("configs.nvim-cheat")
require("configs.cmp")
require("configs.lsp.mason")
require("configs.lsp.handlers")
require("configs.lsp.null-ls")
-- require("configs.telescope")
require("configs.indentline")
require("configs.autopairs")
require("configs.comment")
--require("configs.lsp_config")
require("configs.spell")
--require("configs.nvim-ufo")
--require("configs.fidget")
--require("configs.vim-test")
--require("configs.chatgtp")
--require("configs.slime")
--require("configs.debug")
--require("configs.orgmode")
require("configs.bufferline")
--[[ require("configs.whichkey") ]]
require("configs.impatient")
-- require("configs.codecompanion")
-- require("configs.dap")
